export const shopConfig = {
  shop: {
    category: [
      { category: "All", description: "Hello world" },
      { category: "Books", description: "Reading equipment for people who read as a hobby" },
      { category: "Posters" },
      { category: "Socks" },
      { category: "Mouse" },
      { category: "TV" },
      { category: "Caterpillar 793F CMD XR9000 MegaHauler - 350 Ton Payload Earth Mover" },
    ],
    products: [
      {
        id: 1,
        title:
          "Black Blink 182 A3 poster with Black Blink 182 A3 poster with frame Black Blink 182 A3 poster with frame",
        description: "High quality plastic",
        by: "Essel Press",
        price: 1200,
        discount: 10,
        imgSrc: "https://picsum.photos/id/1/1200",
        redirectUrl: "google.com",
      },
      {
        id: 1,
        title: "Black Blink 182 A3 poster with frame",
        description: "High quality plastic",
        by: "Essel Press",
        price: 1200,
        discount: 10,
        imgSrc: "https://picsum.photos/id/2/1200",
        redirectUrl: "google.com",
      },
      {
        id: 1,
        title: "Black Blink 182 A3 poster with frame",
        description: "High quality plastic",
        by: "Essel Press",
        price: 1200,
        discount: undefined,
        imgSrc: "https://picsum.photos/id/3/1200",
        redirectUrl: "google.com",
      },
      {
        id: 1,
        title: "Black Blink 182 A3 poster with frame",
        description: "High quality plastic",
        by: "Essel Press",
        price: 1200,
        discount: 10,
        imgSrc: "https://picsum.photos/id/1/1200",
        redirectUrl: "google.com",
      },
      {
        id: 1,
        title: "Black Blink 182 A3 poster with frame",
        description: "High quality plastic",
        by: "Essel Press",
        price: 1200,
        discount: 10,
        imgSrc: "https://picsum.photos/id/1/1200",
        redirectUrl: "google.com",
      },
      {
        id: 1,
        title: "Black Blink 182 A3 poster with frame",
        description: "High quality plastic",
        by: "Essel Press",
        price: 1200,
        discount: 10,
        imgSrc: "https://picsum.photos/id/1/1200",
        redirectUrl: "google.com",
      },
    ],
  },
};
