export const shopConfig = {
  shop: {
    products: [
      {
        id: 1,
        title: "Black Blink 182 A3 poster with Black Blink 182 A3 poster with frame Black Blink 182 A3 poster with frame",
        description: "High quality plastic",
        by: "Essel Press",
        price: 1200,
        discount: 10,
        imgSrc: "https://picsum.photos/id/1/1200",
        redirectUrl: "google.com",
      },
      {
        id: 1,
        title: "Black Blink 182 A3 poster with frame",
        description: "High quality plastic",
        by: "Essel Press",
        price: 1200,
        discount: 10,
        imgSrc: "https://picsum.photos/id/2/1200",
        redirectUrl: "google.com",
      },
      {
        id: 1,
        title: "Black Blink 182 A3 poster with frame",
        description: "High quality plastic",
        by: "Essel Press",
        price: 1200,
        discount: undefined,
        imgSrc: "https://picsum.photos/id/3/1200",
        redirectUrl: "google.com",
      },
      {
        id: 1,
        title: "Black Blink 182 A3 poster with frame",
        description: "High quality plastic",
        by: "Essel Press",
        price: 1200,
        discount: 10,
        imgSrc: "https://picsum.photos/id/1/1200",
        redirectUrl: "google.com",
      },
      {
        id: 1,
        title: "Black Blink 182 A3 poster with frame",
        description: "High quality plastic",
        by: "Essel Press",
        price: 1200,
        discount: 10,
        imgSrc: "https://picsum.photos/id/1/1200",
        redirectUrl: "google.com",
      },
      {
        id: 1,
        title: "Black Blink 182 A3 poster with frame",
        description: "High quality plastic",
        by: "Essel Press",
        price: 1200,
        discount: 10,
        imgSrc: "https://picsum.photos/id/1/1200",
        redirectUrl: "google.com",
      },
    ],
  },
};
